
// IATA airport code mapping for Google Flights search
const citiesData = [
  { name: "France", airportCode: "CDG", video: "France.mp4", posterImage: "france.jpg", posterText: "Experience the charm of France with its romantic cities and world-class cuisine." },
  { name: "Egypt", airportCode: "CAI", video: "Egypt.mp4", posterImage: "egypt.jpg", posterText: "Explore the ancient wonders and vibrant culture of Egypt." },
  { name: "Argentina", airportCode: "EZE", video: "Argentina.mp4", posterImage: "argentina.jpg", posterText: "Feel the rhythm of tango and the thrill of Patagonian landscapes." },
  { name: "Bolivia", airportCode: "VVI", video: "Bolivia.mp4", posterImage: "bolivia.jpg", posterText: "Adventure through Bolivia's highlands and salt flats." },
  { name: "Brazil", airportCode: "GRU", video: "Brazil.mp4", posterImage: "brazil.jpg", posterText: "Dance through the vibrant streets of Rio and lush Amazon rainforests." },
  { name: "Chile", airportCode: "SCL", video: "Chile.mp4", posterImage: "chile.jpg", posterText: "From desert to glaciers, Chile's landscapes are unmatched." },
  { name: "Colombia", airportCode: "BOG", video: "Colombia.mp4", posterImage: "colombia.jpg", posterText: "Colorful cities and coffee hills await in Colombia." },
  { name: "Peru", airportCode: "LIM", video: "Peru.mp4", posterImage: "peru.jpg", posterText: "Walk in the footsteps of the Incas through ancient Peru." },
  { name: "Ghana", airportCode: "ACC", video: "Ghana.mp4", posterImage: "ghana.jpg", posterText: "Discover Ghana's rich heritage and warm hospitality." },
  { name: "Kenya", airportCode: "NBO", video: "Kenya.mp4", posterImage: "kenya.jpg", posterText: "Witness the majestic wildlife and landscapes of Kenya." },
  { name: "Morocco", airportCode: "CMN", video: "Morocco.mp4", posterImage: "morocco.jpg", posterText: "Stroll through colorful souks and desert dunes in Morocco." },
  { name: "India", airportCode: "DEL", video: "India.mp4", posterImage: "india.jpg", posterText: "A kaleidoscope of colors, cultures, and spirituality." },
  { name: "China", airportCode: "PEK", video: "China.mp4", posterImage: "china.jpg", posterText: "Explore ancient dynasties and modern marvels in China." },
  { name: "Japan", airportCode: "NRT", video: "Japan.mp4", posterImage: "japan.jpg", posterText: "Balance tradition and technology in beautiful Japan." },
  { name: "Kyrgyzstan", airportCode: "FRU", video: "Kyrgyzstan.mp4", posterImage: "kyrgyzstan.jpg", posterText: "Mountains, nomads, and untouched natural beauty." },
  { name: "Myanmar", airportCode: "RGN", video: "Myanmar.mp4", posterImage: "myanmar.jpg", posterText: "Golden pagodas and timeless traditions await in Myanmar." },
  { name: "Canada", airportCode: "YYZ", video: "Canada.mp4", posterImage: "canada.jpg", posterText: "Vast wilderness and welcoming cities in Canada." },
  { name: "Mexico", airportCode: "MEX", video: "Mexico.mp4", posterImage: "mexico.jpg", posterText: "From beaches to pyramids, discover magical Mexico." },
  { name: "USA", airportCode: "JFK", video: "USA.mp4", posterImage: "usa.jpg", posterText: "Explore diverse landscapes and cultures across America." },
  { name: "Belgium", airportCode: "BRU", video: "Belgium.mp4", posterImage: "belgiumPoster", posterText: "Belgium is a hidden gem of Europe, with medieval towns, chocolate, and a rich history of art." },
  { name: "Croatia", airportCode: "ZAG", video: "Croatia.mp4", posterImage: "croatiaPoster", posterText: "From Dubrovnik's ancient walls to the stunning Adriatic coast, Croatia is full of surprises." },
  { name: "England", airportCode: "LHR", video: "England.mp4", posterImage: "englandPoster", posterText: "Explore the charm of English countryside and iconic cities like London and Oxford." },
  { name: "Germany", airportCode: "FRA", video: "Germany.mp4", posterImage: "germanyPoster", posterText: "From fairytale castles to vibrant cities, Germany offers a unique blend of tradition and innovation." },
  { name: "Ireland", airportCode: "DUB", video: "Ireland.mp4", posterImage: "irelandPoster", posterText: "Ireland's green hills, lively pubs, and rich folklore make it a must-visit destination." },
  { name: "Italy", airportCode: "FCO", video: "Italy.mp4", posterImage: "italyPoster", posterText: "Enjoy Italian cuisine, historic landmarks, and beautiful coastlines from Rome to Venice." },
  { name: "Netherlands", airportCode: "AMS", video: "Netherland.mp4", posterImage: "netherlandsPoster", posterText: "The Netherlands enchants with tulip fields, windmills, and the artistic charm of Amsterdam." },
  { name: "Norway", airportCode: "OSL", video: "Norway.mp4", posterImage: "norwayPoster", posterText: "Norway's fjords, northern lights, and Viking heritage await your discovery." },
  { name: "Poland", airportCode: "WAW", video: "Poland.mp4", posterImage: "polandPoster", posterText: "Explore medieval towns, mountains, and the cultural heart of Eastern Europe in Poland." },
  { name: "Portugal", airportCode: "LIS", video: "Portugal.mp4", posterImage: "portugalPoster", posterText: "Portugal offers sunny beaches, historic cities, and world-famous cuisine." },
  { name: "Russia", airportCode: "SVO", video: "Russia.mp4", posterImage: "russiaPoster", posterText: "Discover Russia's imperial cities, vast landscapes, and iconic cathedrals." },
  { name: "Spain", airportCode: "MAD", video: "Spain.mp4", posterImage: "spainPoster", posterText: "Dance with passion in Spain, where flamenco, tapas, and historic marvels come alive." },
  { name: "Sweden", airportCode: "ARN", video: "Sweden.mp4", posterImage: "swedenPoster", posterText: "Sweden invites you to explore its forests, design culture, and progressive lifestyle." },
  { name: "Switzerland", airportCode: "ZRH", video: "Switzerland.mp4", posterImage: "switzerlandPoster", posterText: "Home to the Alps, Switzerland offers unmatched nature, chocolate, and serenity." },
  { name: "Turkey", airportCode: "IST", video: "Turkeya.mp4", posterImage: "turkeyPoster", posterText: "Straddling Europe and Asia, Turkey is a fusion of empires, flavors, and ancient cities." },
  { name: "Palestine", airportCode: "TLV", video: "Palestine.mp4", posterImage: "palestinePoster", posterText: "Palestine is rich with heritage, history, and spiritual significance." },
  { name: "UAE", airportCode: "DXB", video: "UAE.mp4", posterImage: "uaePoster", posterText: "A land of skyscrapers and deserts, the UAE blends modern luxury with Bedouin tradition." },
  { name: "Saudia", airportCode: "RUH", video: "Saudia.mp4", posterImage: "saudiaPoster", posterText: "From ancient ruins to modern marvels, Saudi Arabia is opening its doors to the world." },
  { name: "Cuba", airportCode: "HAV", video: "Cuba.mp4", posterImage: "cubaPoster", posterText: "Cuba offers colonial charm, vintage cars, and Caribbean rhythms." },
  { name: "Cambodia", airportCode: "PNH", video: "Malaysia.mp4", posterImage: "cambodiaPoster", posterText: "Explore ancient temples and vibrant markets in the heart of Southeast Asia." },
  { name: "Taiwan", airportCode: "TPE", video: "Romania.mp4", posterImage: "taiwanPoster", posterText: "Taiwan's mountains, tech cities, and street food make it unforgettable." },
  { name: "Thailand", airportCode: "BKK", video: "Scotland.mp4", posterImage: "thailandPoster", posterText: "From temples to tropical islands, Thailand is pure paradise." },
  { name: "SouthKorea", airportCode: "ICN", video: "South Korea.mp4", posterImage: "southKoreaPoster", posterText: "South Korea is a dynamic mix of high-tech cities and ancient palaces." },
  { name: "Tunisia", airportCode: "TUN", video: "Tunisia.mp4", posterImage: "tunisiaPoster", posterText: "Tunisia is a treasure trove of Roman ruins, Mediterranean beaches, and Sahara dunes." },
  { name: "Madagascar", airportCode: "TNR", video: "Madagascar.mp4", posterImage: "madagascarPoster", posterText: "An island of biodiversity, Madagascar offers adventures like no other." },
  { name: "southAfrica", airportCode: "JNB", video: "Kenya.mp4", posterImage: "southAfricaPoster", posterText: "South Africa dazzles with wildlife, culture, and dramatic landscapes." },
  { name: "Namibia", airportCode: "WDH", video: "Madagascar.mp4", posterImage: "namibiaPoster", posterText: "Namibia's deserts and wildlife safaris are a dream for explorers." },
  { name: "Zambia", airportCode: "LUN", video: "Kenya.mp4", posterImage: "zambiaPoster", posterText: "Home to Victoria Falls, Zambia is an untouched natural wonder." },
  { name: "Mozambique", airportCode: "MPM", video: "Madagascar.mp4", posterImage: "mozambiquePoster", posterText: "Mozambique's coastlines and culture are full of soul and beauty." },
  { name: "HongKong", airportCode: "HKG", video: "Japan.mp4", posterImage: "hongKongPoster", posterText: "Where East meets West, Hong Kong is a city of contrasts." },
  { name: "Indonesia", airportCode: "CGK", video: "Romania.mp4", posterImage: "indonesiaPoster", posterText: "Indonesia is a tropical archipelago filled with islands and adventures." },
  { name: "Malaysia", airportCode: "KUL", video: "Malaysia.mp4", posterImage: "malaysiaPoster", posterText: "Malaysia blends modern cities with lush jungles and cultural diversity." },
  { name: "Maldives", airportCode: "MLE", video: "Cuba.mp4", posterImage: "maldivesPoster", posterText: "Maldives is the epitome of luxury and turquoise water escapes." },
  { name: "Denmark", airportCode: "CPH", video: "Sweden.mp4", posterImage: "denmarkPoster", posterText: "Denmark offers stylish cities, Viking history, and a cozy lifestyle." },
  { name: "Finland", airportCode: "HEL", video: "Poland.mp4", posterImage: "finlandPoster", posterText: "Finland is the land of saunas, northern lights, and endless lakes." },
  { name: "Iceland", airportCode: "KEF", video: "Iceland.mp4", posterImage: "icelandPoster", posterText: "Iceland's volcanoes, geysers, and glaciers will leave you in awe." },
  { name: "Romania", airportCode: "OTP", video: "Romania.mp4", posterImage: "romaniaPoster", posterText: "Discover Romania's castles, Carpathians, and colorful culture." },
  { name: "Scotland", airportCode: "EDI", video: "Scotland.mp4", posterImage: "scotlandPoster", posterText: "Scotland's lochs, whisky, and legends make it magical." },
  { name: "Serbia", airportCode: "BEG", video: "Portugal.mp4", posterImage: "serbiaPoster", posterText: "Serbia is a Balkan beauty rich in nightlife, history, and warmth." },
  { name: "Panama", airportCode: "PTY", video: "Norway.mp4", posterImage: "panamaPoster", posterText: "Panama connects continents and surprises with beaches and biodiversity." },
  { name: "CostaRica", airportCode: "SJO", video: "Kyrgyzstan.mp4", posterImage: "costaRicaPoster", posterText: "Costa Rica is a green paradise of rainforests and wildlife." },
];

export default citiesData;
